### ISSUE TITLE
configs文件夹缺少text.json

### ISSUE THREAD

**Issue by hilllllih** [IshtarTang/weibo_spider-scrapy#2]
自己摸索着解决了，就是把`scrapy_weiboSpider/config_path_file.py`这个文件里的路径改成`n1_userWb_config.json`
我不太懂代码，不知道是我这边的问题还是作者忘记改

谢谢作者写出好用的工具，终于可以备份评论了 ：）

**Comment by IshtarTang** [comment]
是我的问题，上次debug把路径写成测试用的配置文件路径，弄完忘记改回来了，谢谢提醒
